version: "3"

includes:
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend
  ml:
    taskfile: ./ml/Taskfile.yml
    dir: ./ml

tasks:
  up:
    desc: "Start all microservices with Docker Compose"
    cmds:
      - docker compose up -d --build

  down:
    desc: "Stop all Docker Compose microservices"
    cmds:
      - docker compose down