openapi: 3.0.3
servers:
  - url: http://0.0.0.0:8000
    description: Local Development
  - url: http://food_backend:8000
    description: Inside the docker container
security: []
info:
  title: Backend API
  version: 1.0.0
  description: Backend для работы анализатора продуктов
  license:
    url: https://github.com/arseniizyk/food-analyser/blob/07936fac66da411a4cb4464d4cb4e53e7f857cec/LICENSE
    name: MIT

tags:
  - name: Backend
    description: операции с данными о продуктах и юзерах

paths:
  /api/v1/health:
    $ref: ./paths/healthcheck.yaml

  /api/v1/analysis/{barcode}:
    $ref: ./paths/analysis_by_barcode.yaml

  /api/v1/analyze/{barcode}:
    $ref: ./paths/analyze.yaml

  /api/v1/auth/google:
    $ref: ./paths/auth_google.yaml
