version: "3"

tasks:
  run:
    desc: "Run flutter app"
    dir: app
    cmds:
      - flutter clean
      - flutter run

  deps:
    desc: "Install Flutter dependencies for mobile app"
    dir: app
    cmds:
      - flutter pub get