version: "3"

tasks:
  build:release:
    desc: "Release build"
    cmds:
      - flutter build apk --release

  run:
    desc: "Run flutter app"
    cmds:
      - flutter clean
      - flutter run

  deps:
    desc: "Install Flutter dependencies for mobile app"
    cmds:
      - flutter pub get