// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetAnalysisByBarcode200JSONResponseBodyGrade.
const (
	GetAnalysisByBarcode200JSONResponseBodyGradeAverage   GetAnalysisByBarcode200JSONResponseBodyGrade = "average"
	GetAnalysisByBarcode200JSONResponseBodyGradeExcellent GetAnalysisByBarcode200JSONResponseBodyGrade = "excellent"
	GetAnalysisByBarcode200JSONResponseBodyGradeGood      GetAnalysisByBarcode200JSONResponseBodyGrade = "good"
	GetAnalysisByBarcode200JSONResponseBodyGradePoor      GetAnalysisByBarcode200JSONResponseBodyGrade = "poor"
)

// Valid indicates whether the value is a known member of the GetAnalysisByBarcode200JSONResponseBodyGrade enum.
func (e GetAnalysisByBarcode200JSONResponseBodyGrade) Valid() bool {
	switch e {
	case GetAnalysisByBarcode200JSONResponseBodyGradeAverage:
		return true
	case GetAnalysisByBarcode200JSONResponseBodyGradeExcellent:
		return true
	case GetAnalysisByBarcode200JSONResponseBodyGradeGood:
		return true
	case GetAnalysisByBarcode200JSONResponseBodyGradePoor:
		return true
	default:
		return false
	}
}

// Defines values for GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk.
const (
	GetAnalysisByBarcode200JSONResponseBodyIngredientsRiskCaution   GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk = "caution"
	GetAnalysisByBarcode200JSONResponseBodyIngredientsRiskDangerous GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk = "dangerous"
	GetAnalysisByBarcode200JSONResponseBodyIngredientsRiskSafe      GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk = "safe"
)

// Valid indicates whether the value is a known member of the GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk enum.
func (e GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk) Valid() bool {
	switch e {
	case GetAnalysisByBarcode200JSONResponseBodyIngredientsRiskCaution:
		return true
	case GetAnalysisByBarcode200JSONResponseBodyIngredientsRiskDangerous:
		return true
	case GetAnalysisByBarcode200JSONResponseBodyIngredientsRiskSafe:
		return true
	default:
		return false
	}
}

// Defines values for GetAnalysisByBarcode200JSONResponseBodyRisksSeverity.
const (
	GetAnalysisByBarcode200JSONResponseBodyRisksSeverityHigh   GetAnalysisByBarcode200JSONResponseBodyRisksSeverity = "high"
	GetAnalysisByBarcode200JSONResponseBodyRisksSeverityLow    GetAnalysisByBarcode200JSONResponseBodyRisksSeverity = "low"
	GetAnalysisByBarcode200JSONResponseBodyRisksSeverityMedium GetAnalysisByBarcode200JSONResponseBodyRisksSeverity = "medium"
)

// Valid indicates whether the value is a known member of the GetAnalysisByBarcode200JSONResponseBodyRisksSeverity enum.
func (e GetAnalysisByBarcode200JSONResponseBodyRisksSeverity) Valid() bool {
	switch e {
	case GetAnalysisByBarcode200JSONResponseBodyRisksSeverityHigh:
		return true
	case GetAnalysisByBarcode200JSONResponseBodyRisksSeverityLow:
		return true
	case GetAnalysisByBarcode200JSONResponseBodyRisksSeverityMedium:
		return true
	default:
		return false
	}
}

// Defines values for Analyze200JSONResponseBodyGrade.
const (
	Analyze200JSONResponseBodyGradeAverage   Analyze200JSONResponseBodyGrade = "average"
	Analyze200JSONResponseBodyGradeExcellent Analyze200JSONResponseBodyGrade = "excellent"
	Analyze200JSONResponseBodyGradeGood      Analyze200JSONResponseBodyGrade = "good"
	Analyze200JSONResponseBodyGradePoor      Analyze200JSONResponseBodyGrade = "poor"
)

// Valid indicates whether the value is a known member of the Analyze200JSONResponseBodyGrade enum.
func (e Analyze200JSONResponseBodyGrade) Valid() bool {
	switch e {
	case Analyze200JSONResponseBodyGradeAverage:
		return true
	case Analyze200JSONResponseBodyGradeExcellent:
		return true
	case Analyze200JSONResponseBodyGradeGood:
		return true
	case Analyze200JSONResponseBodyGradePoor:
		return true
	default:
		return false
	}
}

// Defines values for Analyze200JSONResponseBodyIngredientsRisk.
const (
	Analyze200JSONResponseBodyIngredientsRiskCaution   Analyze200JSONResponseBodyIngredientsRisk = "caution"
	Analyze200JSONResponseBodyIngredientsRiskDangerous Analyze200JSONResponseBodyIngredientsRisk = "dangerous"
	Analyze200JSONResponseBodyIngredientsRiskSafe      Analyze200JSONResponseBodyIngredientsRisk = "safe"
)

// Valid indicates whether the value is a known member of the Analyze200JSONResponseBodyIngredientsRisk enum.
func (e Analyze200JSONResponseBodyIngredientsRisk) Valid() bool {
	switch e {
	case Analyze200JSONResponseBodyIngredientsRiskCaution:
		return true
	case Analyze200JSONResponseBodyIngredientsRiskDangerous:
		return true
	case Analyze200JSONResponseBodyIngredientsRiskSafe:
		return true
	default:
		return false
	}
}

// Defines values for Analyze200JSONResponseBodyRisksSeverity.
const (
	Analyze200JSONResponseBodyRisksSeverityHigh   Analyze200JSONResponseBodyRisksSeverity = "high"
	Analyze200JSONResponseBodyRisksSeverityLow    Analyze200JSONResponseBodyRisksSeverity = "low"
	Analyze200JSONResponseBodyRisksSeverityMedium Analyze200JSONResponseBodyRisksSeverity = "medium"
)

// Valid indicates whether the value is a known member of the Analyze200JSONResponseBodyRisksSeverity enum.
func (e Analyze200JSONResponseBodyRisksSeverity) Valid() bool {
	switch e {
	case Analyze200JSONResponseBodyRisksSeverityHigh:
		return true
	case Analyze200JSONResponseBodyRisksSeverityLow:
		return true
	case Analyze200JSONResponseBodyRisksSeverityMedium:
		return true
	default:
		return false
	}
}

// GetAnalysisByBarcode200JSONResponseBodyGrade defines parameters for GetAnalysisByBarcode.
type GetAnalysisByBarcode200JSONResponseBodyGrade string

// GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk defines parameters for GetAnalysisByBarcode.
type GetAnalysisByBarcode200JSONResponseBodyIngredientsRisk string

// GetAnalysisByBarcode200JSONResponseBodyRisksSeverity defines parameters for GetAnalysisByBarcode.
type GetAnalysisByBarcode200JSONResponseBodyRisksSeverity string

// AnalyzeMultipartBody defines parameters for Analyze.
type AnalyzeMultipartBody struct {
	Image openapi_types.File `json:"image"`

	// UserId Optional user ID (if authenticated). If not provided, analysis is stored only locally on client.
	UserId *string `json:"user_id,omitempty"`
}

// Analyze200JSONResponseBodyGrade defines parameters for Analyze.
type Analyze200JSONResponseBodyGrade string

// Analyze200JSONResponseBodyIngredientsRisk defines parameters for Analyze.
type Analyze200JSONResponseBodyIngredientsRisk string

// Analyze200JSONResponseBodyRisksSeverity defines parameters for Analyze.
type Analyze200JSONResponseBodyRisksSeverity string

// AuthenticateWithGoogleJSONBody defines parameters for AuthenticateWithGoogle.
type AuthenticateWithGoogleJSONBody struct {
	IdToken string `json:"id_token"`
}

// AnalyzeMultipartRequestBody defines body for Analyze for multipart/form-data ContentType.
type AnalyzeMultipartRequestBody AnalyzeMultipartBody

// AuthenticateWithGoogleJSONRequestBody defines body for AuthenticateWithGoogle for application/json ContentType.
type AuthenticateWithGoogleJSONRequestBody AuthenticateWithGoogleJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get analysis by barcode
	// (GET /api/v1/analysis/{barcode})
	GetAnalysisByBarcode(w http.ResponseWriter, r *http.Request, barcode string)
	// Analyze analysis nutrition photo
	// (POST /api/v1/analyze/{barcode})
	Analyze(w http.ResponseWriter, r *http.Request, barcode string)
	// Authenticate with Google
	// (POST /api/v1/auth/google)
	AuthenticateWithGoogle(w http.ResponseWriter, r *http.Request)
	// Healthcheck
	// (GET /api/v1/health)
	Health(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get analysis by barcode
// (GET /api/v1/analysis/{barcode})
func (_ Unimplemented) GetAnalysisByBarcode(w http.ResponseWriter, r *http.Request, barcode string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Analyze analysis nutrition photo
// (POST /api/v1/analyze/{barcode})
func (_ Unimplemented) Analyze(w http.ResponseWriter, r *http.Request, barcode string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate with Google
// (POST /api/v1/auth/google)
func (_ Unimplemented) AuthenticateWithGoogle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Healthcheck
// (GET /api/v1/health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAnalysisByBarcode operation middleware
func (siw *ServerInterfaceWrapper) GetAnalysisByBarcode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "barcode" -------------
	var barcode string

	err = runtime.BindStyledParameterWithOptions("simple", "barcode", chi.URLParam(r, "barcode"), &barcode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "barcode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalysisByBarcode(w, r, barcode)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Analyze operation middleware
func (siw *ServerInterfaceWrapper) Analyze(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "barcode" -------------
	var barcode string

	err = runtime.BindStyledParameterWithOptions("simple", "barcode", chi.URLParam(r, "barcode"), &barcode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "barcode", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Analyze(w, r, barcode)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthenticateWithGoogle operation middleware
func (siw *ServerInterfaceWrapper) AuthenticateWithGoogle(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthenticateWithGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/analysis/{barcode}", wrapper.GetAnalysisByBarcode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/analyze/{barcode}", wrapper.Analyze)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/google", wrapper.AuthenticateWithGoogle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.Health)
	})

	return r
}
